name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:
jobs:
  updator:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@4a4e59637fa62bd6c086a216c7e4c5b457ea9e79
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions
        
      - name: Update!
        env:
          BasicAuthenticator: ${{ secrets.BASICAUTHENTICATOR }}
          GistId: ${{ secrets.GISTID }}
          GithubToken: ${{ secrets.GITHUBTOKEN }}
          RefreshToken: ${{secrets.REFRESHTOKEN}}
        run: deno run --allow-read --allow-env --allow-net ./index.ts
